### ISSUE TITLE
done is not a function

### ISSUE THREAD

**Issue by rakou** [widestage/widestage#100]
After creating, saving and activating my first layer, when  I went to explore by selecting the elements from the layer. When I clicked the lightening icon (run command), I get the error below in the server logs. I also get the error notification with no message on the UI.

```
(node:68679) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:68679) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
^@(node:68682) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
(node:68684) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
/Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^

TypeError: done is not a function
    at /Users/v915525/sandbox/widestage/server/modules-standard/wst-connection-drivers/controllers/db/connect/MONGODB/MONGODB.js:42:9
    at connectCallback (/Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:430:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
worker 68684 died.
worker 68942 born.
/Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:433
          throw err
          ^

TypeError: done is not a function
    at /Users/v915525/sandbox/widestage/server/modules-standard/wst-connection-drivers/controllers/db/connect/MONGODB/MONGODB.js:42:9
    at connectCallback (/Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:527:5)
    at /Users/v915525/sandbox/widestage/node_modules/mongodb/lib/mongo_client.js:430:11
    at process._tickCallback (internal/process/next_tick.js:61:11)
worker 68681 died.
worker 68943 born.
Loaded enviroment production
```

**Comment by StephanusVictor** [comment]
I managed to fix this issue by adding the parameter "dataSource._id" to the connect function call (MONGODB.js, line 765)

connect(dataSource.params.connection, **dataSource._id,** function (err, connect) {

I don't know Javascript nor this codebase, so I don't know what I broke while fixing this. :)

**Comment by rakou** [comment]
> I managed to fix this issue by adding the parameter "dataSource._id" to the connect function call (MONGODB.js, line 765)
> 
> connect(dataSource.params.connection, **dataSource._id,** function (err, connect) {
> 
> I don't know Javascript nor this codebase, so I don't know what I broke while fixing this. :)

It solved the "done" issue, Thanks a lot!

**Comment by rakou** [comment]
I have created a pull request following @StephanusVictor input

commit id: 2bd68d2

https://github.com/widestage/widestage/pull/101
