### ISSUE TITLE
Does Widestage support single sign on ? or can we integrate widestage with any other product easily? Do we have any benchmarks on time to process and generate reports when dealing with large volume of data 

### ISSUE THREAD

**Issue by chansdad** [widestage/widestage#102]
I am curious to know how easy it is to integrate widestage for seamless authentication and allowing users to create their own reports. And how flexible is it with respect to changing colors and styling so it is integrated well with a web application.
Sure it is looking to be a great software , would also like to know if there are any benchmarks or stress testing that was done , how much volume of data can widestage handle ? Is widestage positioned for operational analytics with fewer data sets or historical datasets with very large data sets. is there plan to include AI algorithms as well?

**Comment by beevou** [comment]
Hi, @chansdad , please use the widestage.com contact form as this space is just for issues.

Thanks
