### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by bsriganesh** [widestage/widestage#104]
![Error1](https://user-images.githubusercontent.com/64227504/80145167-60614a00-85cd-11ea-9837-5783c7d96cd5.JPG)
![Error1](https://user-images.githubusercontent.com/64227504/80145178-648d6780-85cd-11ea-85f2-669ee49d03bd.JPG)

**Comment by beevou** [comment]
Hi @bsriganesh , please take a look at the bower documentation, permissions , etc...

Closing this as is not a widestage issue.

Thanks
Hermes
