### ISSUE TITLE
MySQL Query not working in explorer

### ISSUE THREAD

**Issue by bigboss97lnt** [widestage/widestage#107]
This error occurs after trying to Run a explorer query from Layer's Element added by Query OR even if I added it from the connection! in all cases this error shows up,
it shows in the error **'unicentaopos.undefined'** doesnt exist, but the db name is **unicentaopos** only
this is the error
**Query Error: Query Error: Error: ER_NO_SUCH_TABLE: Table 'unicentaopos.undefined' doesn't exist**

The layer: 
![image](https://user-images.githubusercontent.com/64983216/81433713-b279a200-916d-11ea-90c7-8b59667798bb.png)

The error in explorer page:
![image](https://user-images.githubusercontent.com/64983216/81433966-169c6600-916e-11ea-8c5d-82983dce1f18.png)

**Comment by bigboss97lnt** [comment]
After more test, this error occurs when more than one mysql connections is defined :( is there any workaround can be done ?

**Comment by bigboss97lnt** [comment]
Now its working but not when I drag-drop the elements, I have to click on them so it would work without any errors.
Plus, in public\modules-standard\home\view\index.html there is mistake that was preventing dashboard in public-space from working

>         <i class="fa fa-tachometer-alt"  style="color:#8dc63f"></i>  <a data-nodrag  href="/#/dashboardsv2/{{node.id}}" style="color: slateblue;font-size: larger;font-style: italic;">{{node.title}}</a>

TO 

>         <i class="fa fa-tachometer-alt"  style="color:#8dc63f"></i>  <a data-nodrag  href="/#/dashboard/{{node.id}}" style="color: slateblue;font-size: larger;font-style: italic;">{{node.title}}</a>

sv2 was making a problem, thanks for the nice project but I hope the SQL error gets fixes!

Best regards,
Nasser

**Comment by Quitra01** [comment]
I am having the same problem with a mySQL database.

**Comment by beevou** [comment]
Sorry , we are not able to reproduce this error, see the video making a quick test 
https://youtu.be/5Ovv_u0zSNI
please send more details , like generated SQL captured in the MySQL query logs and any other useful information, like MySQL version and others.

Best
H

**Comment by beevou** [comment]
The public space bug has been corrected @bigboss97lnt , thanks for that

**Comment by Quitra01** [comment]
> 
> 
> Sorry , we are not able to reproduce this error, see the video making a quick test
> https://youtu.be/5Ovv_u0zSNI
> please send more details , like generated SQL captured in the MySQL query logs and any other useful information, like MySQL version and others.
> 
> Best
> H

I checked this out again, and the only difference between a working query REST call and not working query REST call is that for queries that don't work, query.layers array is empty. The rest of the call seems to be the same.

This is the error response: 
```
{
   "result":0,
   "msg":"Query Error: Query Error: Error: ER_NO_SUCH_TABLE: Table 'world.undefined' doesn't exist",
   "sql":"SELECT undefined.Population as wstlped, undefined.SurfaceArea as wstzt FROM undefined undefined GROUP BY undefined.Population, undefined.SurfaceArea LIMIT 0, 500",
   "cleanSQL":"SELECT undefined.Population as \"undefined\", undefined.SurfaceArea as \"undefined\" FROM undefined undefined GROUP BY undefined.Population, undefined.SurfaceArea",
   "time":6
}
```

Simply drag and drop one element and make a query, it gives an error. Drag and drop one element, than click another, doesn't give an error and the query.layers array has the layer that I'm using. 

The array doesn't get populated somehow when you drag and drop is the only thing I can imagine atm.

I hope this helps.

**Comment by clrh** [comment]
Hi,

Just for information, you can give a try to [Urungi](https://github.com/biblibre/urungi/). It is a fork of Widestage. We refactored some parts of the software. You will be maybe luckier.

Regards,
Claire.

**Comment by beevou** [comment]
Hi @Quitra01 , we have tested out again, dragging and dropping just one element, and is working without any issues. The drag and drop are not tied to mySQL or any other specific connection.

Please recreate your layer, as it seems to me that the problem is there.

Also, we can make a remote session if you want to see exactly what is happening there.

Hermes
