### ISSUE TITLE
Doesn't Login

### ISSUE THREAD

**Issue by behrad** [widestage/widestage#14]
Installed on Ubuntu server with node v6 without the `oracledb` package.
When I try yo login, web ui is silent (throwing a console error in my browser) and doesn't log me in.

**Comment by ashfaque1329** [comment]
Installed on CentOS 7 without the oracledb package.When I try yo login, web ui is silent (throwing a console error in my browser - JSON parse errro) and doesn't log me in. Also, some of the ANgular JS http methods used have been deprecated and the code needs refactoring.

**Comment by beevou** [comment]
There is a problem with the version of angular that is installed by default 1.6.4, should be 1.5.5, so if you uninstall all bower packages (remove bower_components folder) and after that you run bower install angular#1.5.5 --save

when asking about the angular version you want to install , be sure you choose the number for the 1.5.5 version

after that the logging should be working.

**Comment by ashfaque1329** [comment]
Cool.I will try that out..Since I had installed angular 1.6.4,I thought
some of the methods need to be changed as they got deprecated in the the
new angular version..so I changed the methods but then I got a JSON parse
error.Now I will do it from scratch n install angular 1.5.5.Thank u!
