### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by sougatabh** [widestage/widestage#17]
npm install and bower install worked well, node server.js leads to below error
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
mongo DB connection
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }

and unable to login. Cannot POST /login.

How to resolve that?

**Comment by sougatabh** [comment]
This is solved but now the issue is bower does not have 1.5.5 angular and updating angular version gives application exception.

**Comment by kimoudev** [comment]
Please can you show how to solve the Login problem

**Comment by beevou** [comment]
There is a problem with the version of angular that is installed by default 1.6.4, should be 1.5.5, so if you uninstall all bower packages (remove bower_components folder)  and after that you run  bower install angular#1.5.5 --save

when asking about the angular version you want to install , be sure you choose the number for the 1.5.5 version

after that the logging should be working.

**Comment by kimoudev** [comment]
Good morning Hermes,

Thanks a lot for your suggestions, everything is working well now.
P.S: May I ask you if it is possible to work together on this project?
I mean, in order to improve it for our own customers ( no open source).

Thanks again for your collaboration.

Regards,

Joachim

2017-03-01 19:50 GMT+01:00 Hermes Romero <notifications@github.com>:

**Comment by beevou** [comment]
Hi @kimoudev ping me at my email (hromero@intalligent.com) and explain me what you need from us, we have a services department and maybe they can help you.

Best
