### ISSUE TITLE
Error while trying to add dataset

### ISSUE THREAD

**Issue by zerotigerds** [widestage/widestage#2]
New installation on a new server. Went fine. Added data sources, tested connection succesfully. We had to add a module for MySQL support first (suggestion: add this step to documentation). Created a new layer with no issue. Went into layer. This is when I ran into problems:
- Clicked "Add new dataset"
- Selected database from drop down (MySQL db)
- The window populates a list of tables successfully
- Selected table(s)
- Clicked "Add to layer"
- Got error notification bar at top of screen

[http://nimb.ws/TdHSCf]

I get this with any database and user (full permission or read only). I get this with any dataset selected (multiple or single).

**Comment by zerotigerds** [comment]
Noticed there were some updated files and did a git pull and retested with same results.

**Comment by beevou** [comment]
Can you send us the structure DML of the tables (create table ....)  you are trying to add to the layer?, probably is because and unsupported field type

**Comment by zerotigerds** [comment]
Sent over email.

**Comment by zerotigerds** [comment]
My team reported this as resolved. They noted:

> Was missing the module ' node-uuid '. Not sure why Widestage didn't include that in their packages.
