### ISSUE TITLE
cannot save report

### ISSUE THREAD

**Issue by lionux2** [widestage/widestage#20]
Hi Guys;

I cannot save reports. Do you know how this can be solved?
Even the administrator, and extended roles do not solve the issue.

Thanks for your help,

P.

**Comment by kimoudev** [comment]
Same for me

Thanks for your help!

**Comment by sdpper** [comment]
Hello - 
Same here too!  Can not save reports.  As a result I removed everything including the mongo collection "widestage" thinking it may be an install issue.    When I reinstalled WideStage it would not create the widestage collection again in mongo.  I got around it by installing WideStage on another system and then copied the mongoDB collection 'widestage' over to the broken system.  Everything came back up but I still can not save reports.  Also not sure what triggers WideStage to create/recreate the widestage collection?  I may play with it some more next weekend. 

Thank you!

**Comment by beevou** [comment]
Please check if after dragging and dropping elements into the report those two buttons appear, "save as report" and "push to a dashboard"

![widestage](https://cloud.githubusercontent.com/assets/2676312/24790233/42e12fb2-1b6e-11e7-9bd1-90afcd6628c5.png)

**Comment by beevou** [comment]
This problem was affecting only MongoDB datasources, now is solved
