### ISSUE TITLE
Add a way to delete or edit a layer name and description

### ISSUE THREAD

**Issue by miniwark** [widestage/widestage#22]
Actually it is only possible to create layer and edit the layer content, i do not see a way to delete them or rename them.

**Comment by beevou** [comment]
You can change the name of a layer, just clicking in the name of the layer when editing the layer, probably is not very intuitive, we will try to make it more intuitive in the next release. Deleting layers is something that we are working on, is not as easy as delete the record in the database, cause all reports and dashboards that depends on that layer that is going to be deleted must be deleted or invalidated also.

![widestage2](https://cloud.githubusercontent.com/assets/2676312/24790742/6b7ae016-1b6f-11e7-81e4-9ef9db9ebdd5.png)
