### ISSUE TITLE
How to add individual fields to a report or dashboard

### ISSUE THREAD

**Issue by jornklung** [widestage/widestage#25]
Hi,
How can we add individual fields from a layer to a report or dashboard?

For example in a layer "Summary" we have two fields "Average Hours" and "Total Hours"
The layer is a single record, but I can't seem to figure out how to display the two above mentioned fields in e.g. a report layout or just get it out as a value and field somewhere without listing it as a table.

**Comment by beevou** [comment]
Probably I am not understanding good enough your problem, but seems that for that, even if the result is just one record you can write an SQL in the layer to be added like any other table or view. If you send us some screenshots for better understanding your problem will be good for us.

Thanks

**Comment by jornklung** [comment]
Hi, 

For example I want to create a dashboard with some aggregates and at the bottom a separate listing of the details.

Hours this week:        130
Hours total project:    990
Hours extra:                320

List of work performed this week:
# | Description | Date | Hours |
1 | Added X  |  01.01.2017 | 7:30
2 | Added Y  |  02.01.2017 | 7:30
3 | Added Z  |  05.01.2017 | 7:30
Etc

The numbers in the first section - how do I add only the field Hours this week - not as a table but just individual values from a layer (first and only record).

**Comment by beevou** [comment]
The best way to do this is with the indicator layout (several indicators, one per metric into the dashboard), but we are working right now on a vertical grid as an alternative
