### ISSUE TITLE
Uncaught TypeError: y.module(...).info is not a function

### ISSUE THREAD

**Issue by jornklung** [widestage/widestage#26]
Running widestage on our server as per instructions we get this error on refreshing the widestage page.

angular-animate.min.js:14 Uncaught TypeError: y.module(...).info is not a function
    at angular-animate.min.js:14
    at angular-animate.min.js:56

Any idea what it can be?

**Comment by beevou** [comment]
Is it the login page or the home page, can you attach one screenshot?

Thanks

**Comment by jornklung** [comment]
This is not shown in the UI, it is listed in console output in Chrome dev view.
It comes when refreshing the page (F5).

**Comment by beevou** [comment]
Thanks, this is solved in the last push

**Comment by rupesh-terase** [comment]
same issue in project 


![image](https://user-images.githubusercontent.com/11422328/39918937-b4aff780-552f-11e8-8597-de90e277cedb.png)
