### ISSUE TITLE
Error while creating a new report

### ISSUE THREAD

**Issue by Marlonc** [widestage/widestage#3]
Hi,

Idk if it's my mistake, but i'm getting this when i try to create a new report on the demo page:

![widestage](https://cloud.githubusercontent.com/assets/7309224/15972217/d2c2fac4-2f02-11e6-84fb-568a684817a2.png)

**Comment by beevou** [comment]
Hi Marlonc, we are not able to reproduce the error, can you give us more info about your operating system, Chrome version , etc... in order to identify the problem?

H

**Comment by beevou** [comment]
![screen shot 2016-07-07 at 08 30 57](https://cloud.githubusercontent.com/assets/2676312/16645623/455b9c42-441d-11e6-995d-4f4458464ed8.png)
