### ISSUE TITLE
create datasource fail when using MongoDB version 3.4.4

### ISSUE THREAD

**Issue by doglasfc** [widestage/widestage#36]
MongoDb version 3.4.4 installed on a remote server with authentication required.  Use same connection string can connect to this database server using Robomongo without any problem, but "test connection" here failed. tried changing mongose version and Mongodb version in package.json file, but does not work...

So does the current version support MongoDB 3.4.4? if not, when it will be fixed?

Thanks!

**Comment by beevou** [comment]
Can you test without authentication and let me know if it works? 

Thanks

**Comment by doglasfc** [comment]
Hi ,

 

The db is on a production server of my client, I’m unable to test that, sorry…

 

Thanks,

 

Chao

**Comment by doglasfc** [comment]
Hi,

 

At beginning, I even can’t login using your default administrator/widestage, once I have change the db string in your config.js, then I’m able to login. After that, when I try to define the data source from this application, I can’t get success. Look into your other configuration file, it looks only support mongodb 2.4.6?

 

Thanks again,

 

Chao

 

From: Chao Fang [mailto:doglasfc@gmail.com] 
Sent: Saturday, April 29, 2017 1:43 PM
To: 'widestage/widestage' <reply@reply.github.com>
Subject: RE: [widestage/widestage] create datasource fail when using MongoDB version 3.4.4 (#36)

 

Hi ,

 

The db is on a production server of my client, I’m unable to test that, sorry…

 

Thanks,

 

Chao

**Comment by beevou** [comment]
We have made some fixes to solve the problem when authenticating with username/ pass in mongo db, please update with the latest version.

Thanks

**Comment by doglasfc** [comment]
Now it works like charm!!!

Thanks

**Comment by doglasfc** [comment]
Hi.

 

Would you please help again? Issue as follows:

 

Since I have created a test layers, but I didn’t find a way to delete it via web interface, so I went to mongo shell and manually delete all items under widestage collection, I was hoping every can start from beginning…

But I got following, How to fix it? Thanks!

 

Chao

 



 

 

From: Chao Fang [mailto:doglasfc@gmail.com] 
Sent: Tuesday, May 2, 2017 10:12 PM
To: 'widestage/widestage' <reply@reply.github.com>
Subject: RE: [widestage/widestage] create datasource fail when using MongoDB version 3.4.4 (#36)

 

Now it works like charm!!!

Thanks

**Comment by doglasfc** [comment]
Never mind, issue fixed by myself.

 

Thanks!

 

 

From: Chao Fang [mailto:doglasfc@gmail.com] 
Sent: Wednesday, May 3, 2017 11:24 PM
To: 'widestage/widestage' <reply@reply.github.com>
Subject: RE: [widestage/widestage] create datasource fail when using MongoDB version 3.4.4 (#36)

 

Hi.

 

Would you please help again? Issue as follows:

 

Since I have created a test layers, but I didn’t find a way to delete it via web interface, so I went to mongo shell and manually delete all items under widestage collection, I was hoping every can start from beginning…

But I got following, How to fix it? Thanks!

 

Chao

 



 

 

From: Chao Fang [mailto:doglasfc@gmail.com] 
Sent: Tuesday, May 2, 2017 10:12 PM
To: 'widestage/widestage' <reply@reply.github.com <mailto:reply@reply.github.com> >
Subject: RE: [widestage/widestage] create datasource fail when using MongoDB version 3.4.4 (#36)

 

Now it works like charm!!!

Thanks
