### ISSUE TITLE
One to one join for MongoDB resulting in cross join

### ISSUE THREAD

**Issue by janfeyen** [widestage/widestage#37]
Hi
I have setup the widestage server and I want to use it on top of a MongoDB.
I have created a simple layer with some relations but when I want to explore it, it looks like it does a cross join on a one to one relationship.

The layer:
![layer](https://cloud.githubusercontent.com/assets/13327928/25738136/be53ceb6-317b-11e7-8c19-f80829c55cc3.PNG)

Explore results:
![explore](https://cloud.githubusercontent.com/assets/13327928/25738143/c9fe746e-317b-11e7-8113-220710be3630.PNG)

The data in Mongo:
![picups](https://cloud.githubusercontent.com/assets/13327928/25738148/d40af1c6-317b-11e7-9751-9a3c6c413525.PNG)

![vehicles](https://cloud.githubusercontent.com/assets/13327928/25738153/da20376a-317b-11e7-8884-4c3cdb8f0ca8.PNG)

The filtering also doesn't work, not sure if this is related to the above problem?

**Comment by beevou** [comment]
This is solved in the latest push

Thanks
