### ISSUE TITLE
MySQL - Gets tables/views from All schema, should only be from one specified in connection.

### ISSUE THREAD

**Issue by lrirwin** [widestage/widestage#38]
Just installed widestage and set up a MySQL connection to the database "prexupa". There are 7 "prexxxx" databases and 3 or 4 other non-related databases on that MySQL instance. When adding a layer, all unique tablenames and unique views across all database instances appear as choices. Almost none of the tables or view are from the database "prexupa".

**Comment by beevou** [comment]
This is already fixed in the last push, now if you setup a database then you will see only the tables from that database, if you do not setup a database in the connection parameters, then you will see all tables from all databases, except system related
