### ISSUE TITLE
Building error on windows

### ISSUE THREAD

**Issue by albertotn** [widestage/widestage#4]
Hi! I've tried to build groupthink today on my system:

windows 8
npm 2.15.1
bower 1.7.9
grunt-cli v1.2.0
grunt v1.0.1

and get following error

c:\temp\widestage\widestage>npm install
npm WARN deprecated jade@1.8.2: Jade has been renamed to pug, please install the
 latest version of pug instead of jade
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated
. Please use 'any-promise' instead.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a bu
ild toolchain, use it instead!
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongod
b-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerD
ependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it
explicitly.

> oracledb@1.7.1 install c:\temp\widestage\widestage\node_modules\oracledb
> node-gyp rebuild

/
c:\temp\widestage\widestage\node_modules\oracledb>if not defined npm_config_node
_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\nod
e_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files (x86)\Python\python.EX
E" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\temp\widestage\widestage\node_modules\oracledb
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/
> kerberos@0.0.21 install c:\temp\widestage\widestage\node_modules\mongodb\node_
modules\kerberos
> (node-gyp rebuild) || (exit 0)

c:\temp\widestage\widestage\node_modules\mongodb\node_modules\kerberos>if not de
fined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "
" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Program Files (x86)\Python\python.EX
E" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:477:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\temp\widestage\widestage\node_modules\mongodb\node_modules\kerbe
ros
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

> kerberos@0.0.11 install c:\temp\widestage\widestage\node_modules\mongoose\node
_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

c:\temp\widestage\widestage\node_modules\mongoose\node_modules\mongodb\node_modu
les\kerberos>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\n
ode_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
ebuild )  else (node "" rebuild )

> bson@0.2.22 install c:\temp\widestage\widestage\node_modules\mongoose\node_mod
ules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

c:\temp\widestage\widestage\node_modules\mongoose\node_modules\mongodb\node_modu
les\bson>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_
modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebui
ld )  else (node "" rebuild )
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! oracledb@1.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oracledb@1.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oracledb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oracledb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls oracledb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\temp\widestage\widestage\npm-debug.log

Seee attached log: 
[npm-debug.zip](https://github.com/widestage/widestage/files/337026/npm-debug.zip)

**Comment by beevou** [comment]
Thanks for your feedback...
These errors are for the installation of the oracledb libraries, as oracle is not supported yet by widestage, it has no consequences in the actual widestage version.

**Comment by albertotn** [comment]
You are welcome, but it's possible to avoid this error and get a widestage working installation ?
