### ISSUE TITLE
install npm takes forever when the ubuntu 16.04 has joined AD domain

### ISSUE THREAD

**Issue by doglasfc** [widestage/widestage#40]
Hi,
I have an ubuntu 16.04 server which has been joined windows AD domain. I'm going to install widestage on it as the MongoDB report server. when I try to run "sudo npm install", it installation process hanging...

I do install it successfully on a same server which didn't join the AD domain. so please tell me, this is the issue or not?

Thanks!

**Comment by beevou** [comment]
Have you check your internet connection from that server, this is something related to your npm install and your server, nothing related to widestage.

**Comment by doglasfc** [comment]
Yes, this server is connected to internet, otherwise I can’t run first two steps: install nodejs and npm.

 

Now the real issue was that it took long time finish the step “sudo npm install”, then after running bower install,  I do get login screen, but I can’t login using administrator/widestage, it returned “rpt.mydomain.com/login” at url of browser and white page, checked mondodb widestage database, nothing happened…
