### ISSUE TITLE
mongoose deprecation warning

### ISSUE THREAD

**Issue by rizzopablo** [widestage/widestage#42]
Is this normal? Or is it actually an error?

node server.js local
forking  0
forking  1
forking  2
forking  3
mongo DB connection
mongo DB connection
mongo DB connection
mongo DB connection
Server running at http://127.0.0.1:8081/ in worker 4
(node:16742) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Server running at http://127.0.0.1:8081/ in worker 3
Mongoose connection open to localhost:27017/widestage_local
(node:16736) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose connection open to localhost:27017/widestage_local
Server running at http://127.0.0.1:8081/ in worker 2
(node:16735) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Server running at http://127.0.0.1:8081/ in worker 1
(node:16729) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Mongoose connection open to localhost:27017/widestage_local
Mongoose connection open to localhost:27017/widestage_local

**Comment by beevou** [comment]
This is normal
