### ISSUE TITLE
Can't generate flat report from embedded  mongodb data source

### ISSUE THREAD

**Issue by doglasfc** [widestage/widestage#43]
I have objects stored in mongodb. each as below:

{
    "_id" : ObjectId("591bde9a272aa6178251f5d0"),
    "c_obj" : ObjectId("591bde9a272aa6178251f54c"),
    "name" : "Mechanical_Tag1",
    "description" : "Description of Mechanical_Tag1",
    "status" : "current",
    "rev" : 0,
    "interfaces" : [ 
        {
            "i_name" : "MT_interface1",
            "exposed" : [ 
                {
                    "p_name" : "P1",
                    "p_description" : "P1_Desc",
                    "p_value" : "P1Value"
                }, 
                {
                    "p_name" : "P2",
                    "p_description" : "P2_Desc",
                    "p_value" : "P2Value"
                }
            ],
            "deny_member" : ObjectId("591be03b272aa61782529210"),
            "properties_edit_member" : ObjectId("591be03b272aa61782529211")
        }, 
        {
            "i_name" : "MT_interface2",
            "exposed" : [ 
                {
                    "p_name" : "P1",
                    "p_description" : "P1_Desc",
                    "p_value" : "P1Value"
                }, 
                {
                    "p_name" : "P2",
                    "p_description" : "P2_Desc",
                    "p_value" : "P2Value"
                }
            ],
            "deny_member" : ObjectId("591be03b272aa61782529212"),
            "properties_edit_member" : ObjectId("591be03b272aa61782529213")
        }
    ],
    "l_relations" : [],
    "r_relations" : [],
    "attached_files" : [ 
        {
            "f_name" : "t1.txt",
            "f_description" : "test text file",
            "f_obj" : ObjectId("591bec06272aa61782550310")
        }
    ],
    "edit_member" : ObjectId("591bde9a272aa6178251f54d"),
    "deny_member" : ObjectId("591bde9a272aa6178251f54e")
}

Now, I drag & drop  "name",  "p_name", "p_description"  as columns on Explore of widestage,  no sample data displayed... Does this software support generating "flat" report from embedded  mongodb data source?

**Comment by beevou** [comment]
Can you test this with the new version uploaded today?

Thanks

**Comment by doglasfc** [comment]
just test it, issue is still there. based my example data, when I drag & drop "name" and "p_name" on explore, it should display result as below:
Mechanical_Tag1      P1
Mechanical_Tag1      P2
but right now query result is empty when i drag & drop "p_name"....

same example data tested on SlamData works... but I like your "drag&drop" features....

anyway, I like new GUI you did, thanks!

**Comment by doglasfc** [comment]
two more suggestions:
1. add layer "delete" function, right now I have to do it from database directly.
2. not easy to delete relationship line between two mongodb collections

**Comment by jmarlett93** [comment]
Looks like we're running into this issue as well.  Are there any updates or potential workarounds?

**Comment by beevou** [comment]
Hi @jmarlett93 , for now, widestage only supports up to two level object nesting in mongoDB, up to which level do you need to have access? Post here a sample of your doc and let us know what data you are not able to see. We are planning to improve this in future releases.

**Comment by miqmago** [comment]
I've found the problem is that mongo is launching this error:

**Comment by miqmago** [comment]
For example could be in `server/core/db/mongodb.js` line 980:

```js

        fields = Object.keys(fields).reduce((newFields, key) => {
            newFields[key.replace(/\./g, '-_-')] = fields[key];
            return newFields;
        }, {});
```

Then it should be replaced back in lines 1025, 1067:

```js
var dbField = field.replace(/-_-/g, '.');
```

And use `dbField` on `if` statements

Tested locally seems to work, what does not seem to work is `sort`, but at least can extract data.
If that sounds good I can make a pull request.
