### ISSUE TITLE
Executing Report Shows Blank Screen

### ISSUE THREAD

**Issue by trackchris** [widestage/widestage#44]
I'm unable to view any created reports - I just get the page filter header with nothing below (see screenshot below).

Widestage was installed via git clone a few moments ago, so using the latest commit code. I created a single MongoDB data source (connection tests ok and is running locally), a single layer that joins 2 collections and added 2 fields to the layer. 

I created the report fine and can edit it without issue, it consists of the 2 fields without any sort/filters specified - but I just can't use the Reports page to display it. 

The following is logged in the browser window when the view report page opens:

```
angular.js:13550 Error: [$injector:unpr] http://errors.angularjs.org/1.5.5/$injector/unpr?p0=uiGridConstantsProvider…20%3C-%20report_viewCtrl%20%3C-%20report_viewCtrl%20%3C-%20report_viewCtrl
    at http://localhost/angular/angular.min.js:6:412
    at http://localhost/angular/angular.min.js:43:84
    at Object.d [as get] (http://localhost/angular/angular.min.js:40:344)
    at http://localhost/angular/angular.min.js:43:146
    at d (http://localhost/angular/angular.min.js:40:344)
    at e (http://localhost/angular/angular.min.js:41:78)
    at Object.instantiate (http://localhost/angular/angular.min.js:41:441)
    at http://localhost/angular/angular.min.js:89:309
    at link (http://localhost/angular-route/angular-route.min.js:7:268)
    at ja (http://localhost/angular/angular.min.js:80:350) <div ng-view="" ng-intro-options="IntroOptions" ng-intro-method="CallMe" class="ng-scope">
```

I also made sure angular 1.5.5 and angular-animate 1.5.5 were both installed during bower install stage.

![image](https://cloud.githubusercontent.com/assets/11329036/26509447/b812d250-4250-11e7-9e81-819b85771360.png)

Using Chrome 58.0.3029.110 (64-bit) on Mac OSX Sierra.

Running server.js on node v6.2.2

Let me know if you need any other info and/or further tests carried out. Thanks!

**Comment by trackchris** [comment]
Just a further update - if I add the report to a dashboard it works fine there. So the issue does seem specific to the 'My Reports' area.

**Comment by trackchris** [comment]
Right, I've narrowed it down. Commit `6973829` appears to be where the problem started. 

When I do a git reset --hard to the previous commit of `1a34469` its working 👍

**Comment by beevou** [comment]
The latest update is fixed now
