### ISSUE TITLE
Can't login with Mongo authentication enabled?!

### ISSUE THREAD

**Issue by tr37ion** [widestage/widestage#49]
For security reasons I installed MongoDB with authorization enabled as shown here 

https://docs.mongodb.com/manual/tutorial/enable-authentication/

I assume, MongoDB authentication (user/pw) is a problem for Widestage. I can see the Widestage login screen but I can't login. I changed the http port as another service is already running on port 80. The CLI shows

```
mongo DB connection
Mongoose connection open to mongodb://localhost:27017/widestage
no records in the users model, this is the initial setup!
crypto.js:635
    throw new TypeError(
    ^

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at RandomBytes.ondone (/srv/widestage/server/util/hash.js:39:20)
mongo DB connection
Server running at http://0.0.0.0:28283/ in worker 5
Mongoose connection open to mongodb://localhost:27017/widestage
```

**Comment by floushee** [comment]
I have the same problem without mongo authorization .

**Comment by tr37ion** [comment]
I'm with version v8.0.0. 

I was of the impression there is no user based database authentication in Widestage because the database connection string doesn't  https://github.com/widestage/widestage/blob/master/server/config/config.js#L47 that's why I started changing the code, which is possibly not needed. 

I didn't finish or test it as I got interrupted. At that time this was the idea:

```diff
diff --git a/server/config/mongoose.js b/server/config/mongoose.js
index 0af3c54..47125e5 100644
--- a/server/config/mongoose.js
+++ b/server/config/mongoose.js
@@ -1,6 +1,16 @@
 module.exports = function (mongoose, done) {
 
     var dbURI = config.db;
+
+    var dboptions = {
+      db: { native_parser: true },
+      server: { poolsize: 5 },
+      ssl: false,
+      autoreconnect: false,
+      user: 'dbwidestageuser',
+      password: 3wFMH8jGy3'
+    }
+
     if (config.db_type == 'tingoDB')
         {
             //global.connection = mongoose.connect('tingodb:'+global.tingo_db_path);
@@ -13,7 +23,7 @@ module.exports = function (mongoose, done) {
         } else {
             console.log('mongo DB connection');
             var mongoose = require('mongoose');
-            global.connection = mongoose.createConnection(dbURI,{ server: { poolSize: 5 } });
+            global.connection = mongoose.createConnection(dbURI, dboptions);
 
             // CONNECTION EVENTS
             // When successfully connected
@@ -46,11 +56,8 @@ module.exports = function (mongoose, done) {
         });
     });
 
-
-
     var fs = require('fs');
 
-
     //Custom models
     var models_dir = __dirname + '/../custom';
     fs.readdirSync(models_dir).forEach(function (file) {

```

**Comment by kimoudev** [comment]
Finish MongoDB with authorization enabled works? please @tr37ion @beevou

**Comment by tr37ion** [comment]
@kimoudev not sure what you mean with this. Currently, I'm fairly busy with other stuff. I didn't test it. That's why I published what I did so far. Maybe someone else can try. I hope, I can find time the next two weeks to look into it. ... no guarantee. :)

**Comment by beevou** [comment]
We are working on it, it will be solved in the upcoming days.

**Comment by tr37ion** [comment]
Fine, thank you.

**Comment by willyd61** [comment]
any update on this?

**Comment by beevou** [comment]
We have checked this and is working without any issues, we have made the test against a mongolab database with authentication enabled by default, in a clone from our github repository... 
we only changed the connection details, like this...

go to /server/config/config.js

you will see there the connection details for the different environments, change the db connection in the environment that you are using or all of them, production, development, etc...

you will find a line like this:
db: 'mongodb://localhost:27017/widestage_development',

change that line with your user and password

db: 'mongodb://<user>:<password>@localhost:27017/widestage_development',

after this, start the widestage server and connect with the browser, introduce the administrator/widestage  credentials and here you go...

**Comment by willyd61** [comment]
That still leaves the crypto issue. All of the pbkdf2 function calls in widestage source do not have digest. So this application is still not working. 

TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:635:11)
    at Object.exports.pbkdf2 (crypto.js:623:10)
    at RandomBytes.ondone (/srv/widestage/server/util/hash.js:39:20)

**Comment by beevou** [comment]
That is for sure a problem with your npm, as I mentioned before, that testing was done getting all directly from the github repository and doing the npm install, as with a new installation...

That said if you want to deactivate the crypto then you have to go to the config.js again
and change this:

crypto: {
            enabled: true,
            secret: 'SecretPassphrase'
        },

for this:

crypto: {
            enabled: false,
            secret: 'SecretPassphrase'
        },

that will deactivate the encryption of packages between the server and the client, so if you want encryption you need to setup an https web server...
