### ISSUE TITLE
docker-compose does not completed

### ISSUE THREAD

**Issue by chanupol** [widestage/widestage#50]
I tried to run docker-compose up .but it throws error 

npm ERR! Linux 4.9.27-moby
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

how do I resolve this error.
Thank you.

**Comment by floushee** [comment]
Its so funny that you need a java compiler to build a node.js app :)

You need to extend the Dockerfile and install the java jdk before you build the node.js application.
