### ISSUE TITLE
Export of Dashboards and Reports

### ISSUE THREAD

**Issue by ACAGuerrero** [widestage/widestage#51]
Hello together,

Would it be possible to add an export function which allows to export dashboards and reports? (PDF, PNG, JPEG etc.)?  

This would be a very useful... any thoughts on it?

**Comment by beevou** [comment]
We will add this to the wish list, thanks for your suggestion

**Comment by syrjala25** [comment]
Hi, I can see the button to export report data but it doesn't do anything.  What do I need to configure to activate it? I use the service running in Linux server from Windows7 workstation.
