### ISSUE TITLE
New data source with MongoDB not working  

### ISSUE THREAD

**Issue by k-d-andani** [widestage/widestage#52]
Hello,

I try to create new data source with MongoDB.
But its not working.
Data source for MySQL is working perfectly.
not working for Mongo DB.

Please help

**Comment by beevou** [comment]
We have tested it and is working for us, can you give us more context, like the server error, configuration parameters, etc...

**Comment by k-d-andani** [comment]
thanks for response.

i used ip address ad HOST
port 27000
username , password and db name.
