### ISSUE TITLE
MSSQL generated sql query is incompatible

### ISSUE THREAD

**Issue by paulabinasr** [widestage/widestage#53]
This is the generated SQL query in the Explore tab when i drop a field from a MSSQL datasource through a layer 

SELECT WSTic0q.ColorCode as wsthv FROM dbo.IvColor1ES WSTic0q GROUP BY WSTic0q.ColorCode ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 500 ROWS ONLY

the part "OFFSET...." is incompatible and generates an error.

**Comment by beevou** [comment]
What MSSQL version are you using?
that OFFSET is the standard in MSSQL for v2012 and onwards
http://sqlmag.com/sql-server-2012/using-new-offset-and-fetch-next-options

**Comment by beevou** [comment]
if you are using an older version you can always set up the package size to -1 in the connection to get all rows, without pagination
