### ISSUE TITLE
Error on starting up server

### ISSUE THREAD

**Issue by brianpunzalan** [widestage/widestage#54]
I'm getting the below error not sure if it is an issue on my side or in the code. I followed the installation process.

> events.js:182
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: bind EACCES 0.0.0.0:80
>     at Object._errnoException (util.js:1041:11)
>     at _exceptionWithHostPort (util.js:1064:20)
>     at listenOnMasterHandle (net.js:1402:16)
>     at rr (internal/cluster/child.js:111:12)
>     at Worker.send (internal/cluster/child.js:78:7)
>     at process.onInternalMessage (internal/cluster/utils.js:42:8)
>     at emitTwo (events.js:130:20)
>     at process.emit (events.js:213:7)
>     at emit (internal/child_process.js:774:12)
>     at _combinedTickCallback (internal/process/next_tick.js:141:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by keith-hall** [comment]
I experienced the same thing, I guess it had trouble binding to port 80 - so I ran it with `node server.js local` and it bound to port 8081 instead, as per [`./server/config/config.js`](https://github.com/widestage/widestage/blob/d4d263f485871ccc9593f2ec4cf3dddffff33f0f/server/config/config.js#L84).

**Comment by Chellll** [comment]
Same problem.

**Comment by Chellll** [comment]
Problem disappeared after reinstall ubuntu on vds server.

**Comment by Chellll** [comment]
This error occure when appache2 server run.

**Comment by windforce7** [comment]
If you are having this problem following installation instructions, try the other way:
1. clone the repository
2. install docker and docker-compose (for Ubuntu users, docker-compose can be simply installed by "apt-get install docker-compose" command), start docker daemon
3. cd to the repository directory, make sure you see docker-compose.yml
4. if you have further problem logging in, see #65
