### ISSUE TITLE
Cannot POST /login 

### ISSUE THREAD

**Issue by zagor-cico** [widestage/widestage#57]
Hi,
I'm becoming crazy, I've already tried several ways to avoid this this problem but after server is up I can't login.
Always the same error: Cannot POST /login 
**This is logging page before press the button log in**:

Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=widestage-login&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2F%24injector%2Fmodulerr%3Fp0%3Dui.router%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.5%252F%2524injector%252Fnomod%253Fp0%253Dui.router%250AO%252F%253C%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A6%253A412%250Aje%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A25%253A235%250Ab%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A24%253A282%250Aje%252F%253C%252F%253C%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A25%253A20%250Ag%252F%253C%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A39%253A374%250Aq%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A7%253A353%250Ag%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A39%253A222%250Ag%252F%253C%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A39%253A391%250Aq%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A7%253A353%250Ag%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A39%253A222%250Abb%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A43%253A246%250Ayc%252Fc%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A21%253A19%250Ayc%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A21%253A332%250Aee%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A20%253A156%250A%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A313%253A135%250Ab%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A188%253A487%250AQf%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A37%253A31%250APf%252Fd%2540http%253A%252F%252F10.0.2.15%253A8090%252Fangular%252Fangular.min.js%253A36%253A486%250A%0AO%2F%3C%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A6%3A412%0Ag%2F%3C%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A40%3A134%0Aq%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A7%3A353%0Ag%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A39%3A222%0Ag%2F%3C%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A39%3A391%0Aq%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A7%3A353%0Ag%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A39%3A222%0Abb%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A43%3A246%0Ayc%2Fc%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A21%3A19%0Ayc%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A21%3A332%0Aee%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A20%3A156%0A%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A313%3A135%0Ab%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A188%3A487%0AQf%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A37%3A31%0APf%2Fd%40http%3A%2F%2F10.0.2.15%3A8090%2Fangular%2Fangular.min.js%3A36%3A486%0A

**After press login button here it is logging page:**

Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

Please help me !!!

**Comment by beevou** [comment]
can you give more context, Operating system, versions, etc...
