### ISSUE TITLE
Calling wideStage inside nodeJS application

### ISSUE THREAD

**Issue by ApicalContact** [widestage/widestage#59]
Will I be able to call the widestage inside nodejs application?

**Comment by baradhili** [comment]
I'd like to know also... at the moment I'm looking at how to pass auth across from another app

**Comment by beevou** [comment]
There is no oauth or any other option available in widestage, widestage uses passport so you can extend with oauth or any other

**Comment by clrh** [comment]
How is use the conf google.clientID, clientSecret and callback ? or how do you plan to ? server.config.config.js
