### ISSUE TITLE
Bug that causes filter validation to fail

### ISSUE THREAD

**Issue by puchol** [widestage/widestage#6]
I'm not an expert in Angular/Node development, but I have managed to debug a problem enough to fix it partially. The bug causes a filter in Explore to fail validation no matter what you type in it, thus not allowing the use of filters at all, unless a value is picked using the "select distinct" search.

On line 77 of query-edit.html, a reference is made to filter.searchValue. This element is not present in the HTML, and there are also references to it in /public/js/query/controller.js that use the element for filter validation before a query is re-run. Replacing filter.searchValue with filter.filterText1 in both the HTML file and controller.js (function checkFilters), validation takes place correctly, and queries can be run.

**Comment by beevou** [comment]
Thanks for your comment, we will fix it in the new release.
