### ISSUE TITLE
Trouble getting up and running

### ISSUE THREAD

**Issue by joewagner** [widestage/widestage#60]
Hi All,
I'm trying to get this running locally, and I believe I'm running into issues with dependencies not matching.

Can anyone give a full list of all dependencies and which specific commit from this repo that they have used to get a working version of widestage attached to data in MongoDB?
I've Tried Node 8.6.0, angular 1.5.5, angular-animate 1.5.5, then letting bower and npm decide versions for everything else.
I've Tried Node 6.11.4, angular 1.5.5, angular-animate 1.5.5, again letting bower and npm decide versions.

Along with an assortment of errors surrounding, __what I believe is mis-matched dependencies__, I am trying to run with crypto disabled and I had to set the services to use [`$httpParamSerializerJQLike`](https://docs.angularjs.org/api/ng/service/$httpParamSerializerJQLike).  But that is probably just a versioning issue...

Much appreciation for anyone who can help,

**Comment by baradhili** [comment]
A couple of us have gotten it up and running, you do need the JDK and JRE installed. From the firehose of deprecateds, we probably need to fork this and fix..

I did on the current node 6.x, using their deb install and didn't specifically install angular.. what OS are you running?

**Comment by joewagner** [comment]
@baradhili Thanks for the response.  Ideally I would get this running on Ubuntu 16, but I've been using OSX 10.  
All of the issues I've run into are things like incorrect json serialization/deserialization between angular and express, and five different versions of angular dependencies in Bower.  
This looks to be a fantastic tool, forking and fixing seems tempting...

Any idea what the JDK+JDE are needed for?
Which commit from this repo are you using?
Any chance you would post a full list of versions you have installed?

@beevou any tips on getting this installed and running that haven't made it into the readme yet?

**Comment by baradhili** [comment]
well the java and javac if I remember are needed for one little bit of the
bower install...
I'm running this on a debian 9, so basically ubuntu 16 close enough.

I'd suggest then removing node and angular and reinstalling from the node
ubuntu repo at node.js I think that will remove a lot of your pain with
different versions.. stick with 6x.

I would post the list if I had remembered to capture them at the time!...
