### ISSUE TITLE
Delete layer

### ISSUE THREAD

**Issue by baradhili** [widestage/widestage#62]
Is there a way to delete a layer?

**Comment by beevou** [comment]
Layers have many dependencies, as you can understand, like reports or dashboards using then, so is not just a matter of deleting the layer, the reports or dashboards dependent on this should be removed or invalidated also. at the meantime, you can disable the layer for not to be available anymore to your users.

In the widestage professional version that functionality is implemented, but not in the open source version.

Best
Hermes
