### ISSUE TITLE
Error connection to Mongo using SSL

### ISSUE THREAD

**Issue by littleski** [widestage/widestage#63]
Hello,

When connecting to a mongoDb datasource for which the server use SSL + self signed cert (like compose.io) is not working.

Would be great if you include the needfull options in the mongodb connection create datasource. (i-e SSL true/false, + cert if using SSL (or at least a SSLValidate to false))

got something like
Mongoose default connection error: MongoError: connection 1 to aws-eu-west-1-xxx.3.dblayer.com:xxx closed

In core/db/mongodb.js you use static connection string and do not manage the mongo connections options.

**Comment by telmocontreiras** [comment]
You can include those in the host field:
aws-eu-west-1-xxx.3.dblayer.co?ssl=true

**Comment by littleski** [comment]
the SSL=true part yet, the validation of the certificate or the disabling of validation for the certificate no.

**Comment by telmocontreiras** [comment]
If you're in a pinch, this is where you want to patch it to add your certs:
\server\core\db\mongodb.js

**Comment by littleski** [comment]
That s what i did :)

Le 2 févr. 2018 12:49 PM, "Telmo Contreiras" <notifications@github.com> a
écrit :
