### ISSUE TITLE
Failed at the java@0.8.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by varshithr** [widestage/widestage#64]
Not sure if it's issue rather might be something I am doing wrong.
Couldn't figure out. I hit `npm install` using node version 8.6.0

```
npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/varshith/widestage/npm-debug.log
varshith@varshith:~/widestage$ node -v
v8.6.0
varshith@varshith:~/widestage$ npm -v
5.3.0

```

Can you please help me?

**Comment by baradhili** [comment]
yuo need to install the java jre for the java.. and the next error you get
will will be a missing javac which you can fix by installing the java jdk

**Comment by graysonwright** [comment]
On Ubuntu, I fixed this with:

```
sudo apt-get install -y default-jre default-jdk
```

**Comment by clrh** [comment]
It works for me thanks (upgrading node plus install jre).

**Comment by du8die** [comment]
Experiencing the same issue. 

Node 8.11.1
NPM 5.6.0
JRE and JDK both installed.

ARGH.

**Comment by baradhili** [comment]
Widestage isn't being maintained, so expect it to accumulate deprecated packages... I'm trialling DHIS2 at the moment, which may suit your application

**Comment by iions** [comment]
In case anyone else gets stuck on this, doing the above followed by [this post](
https://medium.com/@jharris.sf/npm-rebuild-elastic-beanstalk-and-permissions-be1c6fceba9a) finally fixed it for me.

**Comment by jonathanseneris** [comment]
In case anyone else gets stuck on this, doing the above followed by [this post](
https://medium.com/@jharris.sf/npm-rebuild-elastic-beanstalk-and-permissions-be1c6fceba9a) finally fixed it for me.

**Comment by kjrajvir** [comment]
@varshithr Do you get solution for this? I face the same problem in CentOS..
