### ISSUE TITLE
Not possible to explore data from MongoDb

### ISSUE THREAD

**Issue by rutemja** [widestage/widestage#67]
Hello,

Steps:
1. Installed Widestage in a Docker container like it is explained.
2. Changed server config like explained to our own mongo db server.
3. Start container -> Widestage is running and login is possible
4. Added a new data source (connection test passes)
5. Added a new layer (collections of data source are present)
6. Activated new layer
7. Tried to get a table of the data via explore, but no query results are displayed and a type error occures (there are data sets in database):
![image](https://user-images.githubusercontent.com/34125451/34769482-3b7657f0-f5fe-11e7-88ef-f6f61202e624.png)
~~8. After clicking around a bit, the container dies.~~ (This was caused by our setup)

Does anyone know what we are doing wrong? Or is it a bug?

**Comment by rutemja** [comment]
Is it possible that this is caused by a mongo update?

> Mongodb 3.6 changed the way the aggregate command works
> 
> "Changed in version 3.4: MongoDB 3.6 removes the use of aggregate command without the cursor option unless the command includes the explain option. Unless you include the explain option, you must specify the cursor option."

**Comment by telmocontreiras** [comment]
We're having the same issue and we're using 3.4

**Comment by miqmago** [comment]
Having the same issue here, tried with multiple versions of mongoose.

Mongodb 3.6
All seems fine, no errors in console, can read collections but when requesting reports or exploring, no data anywhere. Server request works, but `/api/reports/get-data` always returns data with array(0):

```json
{
  "result": 1,
  "data":[],
  "sql":"No SQL available for MongoDB"
}
```

**Comment by spederiva** [comment]
I'm getting the same error! Any solution?

**Comment by pratik28** [comment]
what edits did you do to your config.js  file ?

**Comment by miqmago** [comment]
I've reverted to 3.4 and now it's working fine
