### ISSUE TITLE
BETWEEN SQL filters have a syntax error

### ISSUE THREAD

**Issue by puchol** [widestage/widestage#7]
In file /server/core/db/sql line 885 and following (for the BETWEEN and NOT BETWEEN filters), the correct syntax should be:

result = (filterElementName + ' BETWEEN '+filterValue+' AND '+filter.filterText2);

as otherwise the resulting SQL query does NOT contain the column where the BETWEEN clause applies. Eg. 

... ON (WSTmgpb.uid = WSTc1zd.uid) WHERE BETWEEN 20 AND 80 GROUP BY WSTmgpb.data_balance ...

which should really be:

... ON (WSTmgpb.uid = WSTc1zd.uid) WHERE WSTmgpb.data_balance BETWEEN 20 AND 80 GROUP BY WSTmgpb.data_balance ...

**Comment by beevou** [comment]
Thanks for your contribution, the bug is fixed now and will be available in the next release.
