### ISSUE TITLE
Building error on windows 10 x64

### ISSUE THREAD

**Issue by meneguci** [widestage/widestage#71]
I am having the following problem when trying to install. What can it be?

C:\nodeJS\widestage>npm install

> java@0.8.0 install C:\nodeJS\widestage\node_modules\java
> node-gyp rebuild

C:\nodeJS\widestage\node_modules\java>if not defined npm_config_node_gyp (node "C:\nodeJS\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\nodeJS\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
..\src\javaObject.cpp(116): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vc
xproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(3851): note: see declaration of 'v8::Function::NewInstance'
..\src\javaObject.cpp(349): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vc
xproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(3851): note: see declaration of 'v8::Function::NewInstance'
..\src\java.cpp(897): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(927): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(956): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(983): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(1019): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
..\src\java.cpp(1044): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
  utils.cpp
  win_delay_load_hook.cc
..\src\utils.cpp(347): warning C4996: 'v8::Value::ToInt32': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9796): note: see declaration of 'v8::Value::ToInt32'
..\src\utils.cpp(354): warning C4996: 'v8::Value::ToNumber': was declared deprecated [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  C:\Users\Nicassio\.node-gyp\8.11.1\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
     Creating library C:\nodeJS\widestage\node_modules\java\build\Release\nodejavabridge_bindings.lib and object C:\nodeJS\widestage\node_modules\java\build\Release\no
  dejavabridge_bindings.exp
java.obj : error LNK2001: unresolved external symbol __imp_JNI_CreateJavaVM [C:\nodeJS\widestage\node_modules\java\build\nodejavabridge_bindings.vcxproj]
C:\nodeJS\widestage\node_modules\java\build\Release\nodejavabridge_bindings.node : fatal error LNK1120: 1 unresolved externals [C:\nodeJS\widestage\node_modules\java\b
uild\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nodeJS\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodeJS\\node.exe" "C:\\nodeJS\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\nodeJS\widestage\node_modules\java
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.8.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicassio\AppData\Roaming\npm-cache\_logs\2018-03-31T13_48_46_687Z-debug.log
[2018-03-31T13_48_46_687Z-debug.log](https://github.com/widestage/widestage/files/1865517/2018-03-31T13_48_46_687Z-debug.log)

**Comment by ravituvar** [comment]
Hi @meneguci , have you got any solution on this?

I am getting following..
gyp ERR! configure error                                                                               
gyp ERR! stack Error: Can't find Python executable "C:\Python35\python.exe", you can set the PYTHON env
gyp ERR! stack     at Object.failNoPython (C:\Users\Imedia-32\AppData\Roaming\npm\node_modules\npm\node
:19)                                                                                                   
gyp ERR! stack     at Object.<anonymous> (C:\Users\Imedia-32\AppData\Roaming\npm\node_modules\npm\node_
16)                                                                                                    
gyp ERR! stack     at C:\Users\Imedia-32\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)                                              
gyp ERR! System Windows_NT 10.0.16299                                                                  
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Imedia-32\\AppData\\Roaming\\npm\\no
gyp\\bin\\node-gyp.js" "rebuild"                                                                       
gyp ERR! cwd E:\Downloads\widestage-master\widestage-master\node_modules\java                          
gyp ERR! node -v v6.11.0                                                                               
gyp ERR! node-gyp -v v3.6.2                                                                            
gyp ERR! not ok                                                                                        
npm ERR! code ELIFECYCLE                                                                               
npm ERR! errno 1                                                                                       
npm ERR! java@0.8.0 install: `node-gyp rebuild`                                                        
npm ERR! Exit status 1                                                                                 
npm ERR!                                                                                               
npm ERR! Failed at the java@0.8.0 install script.                                                      
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.     
                                                                                                       
npm ERR! A complete log of this run can be found in:                                                   
npm ERR!     C:\Users\Imedia-32\AppData\Roaming\npm-cache\_logs\2018-04-09T06_10_00_681Z-debug.log     
[2018-04-09T06_10_00_681Z-debug.log](https://github.com/widestage/widestage/files/1888619/2018-04-09T06_10_00_681Z-debug.log)

**Comment by Rahul-Bisht** [comment]
what python version are you using? 
if it is >2.7 then try building with 2.7

**Comment by Rahul-Bisht** [comment]
``Can't find Python executable "C:\Python35\python.exe", you can set the PYTHON env``
do you have python installed (preferably v2.7)?
