### ISSUE TITLE
MySQL datatype timestamp not usable as date

### ISSUE THREAD

**Issue by tuedelue** [widestage/widestage#8]
Hi,
I am using widestage in combination with a local MySQL server. Although I define a certain field with the underlying MySQL-datatype "timestamp" as "Date" within the widestage layer, I cannot use it as an actual date in any query or report - it is rather handled as a any other text key.
Did I miss anything? Are there any tricks to get this working? Is the datatype correctly translated into widestage?
Your help is very appreciated. Many thanks in advance.

**Comment by beevou** [comment]
We are working on a new release, planed by the end of this month, where this problem will be solved, we will let you know as soon as we update the version in github.

Thanks

**Comment by san26786** [comment]
Hi,

Is this resolved?
