### ISSUE TITLE
Can't login on a windows 7 machine

### ISSUE THREAD

**Issue by reipaul** [widestage/widestage#9]
I installed and the login page launched fine but after using the default username/password (administrator/widestage) I'm receiving:
Cannot POST /login 
without any other information. Any suggestions?

**Comment by beevou** [comment]
Can you take a look if there is some kind of error in the developers tools console in chrome, and let us know, we are unable to reproduce.

Thanks

**Comment by shaynem** [comment]
I get the same issue

net::ERR_EMPTY_RESPONSE 

angular.js:12011 POST http://*:8181/api/login net::ERR_EMPTY_RESPONSE

I made sure that mongodb is up and running and that the port etc works to it.

**Comment by carcagi** [comment]
I have the same issue with a Fresh Install on Ubuntu. Any news?

**Comment by beevou** [comment]
Download the latest push
