### ISSUE TITLE
Error launch Docker-compose in widestage

### ISSUE THREAD

**Issue by mspacca** [widestage/widestage#99]
Hi, 
I have this error launch docker-compose in container log widestage: 

**Mongoose default connection disconnected,
Mongoose default connection error: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017,
}]**

where i can change address 127.0.0.1 to mongo address in docker container?
Thanks

**Comment by rakou** [comment]
I am getting the same error.

Mongoose default connection disconnected
Mongoose default connection error: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]

**Comment by beevou** [comment]
Hi @mspacca & @rakou, a new version of the docker files have been pushed.

Please note that when configuring widestage, the mongodb repository has to be mongo, not localhost.

Best
Hermes
